### ISSUE TITLE
Feature.!

### ISSUE THREAD

**Issue by akashnimare** [sdht0/cyberoam-clients#2]
The code works fine in linux.It would be very nice IF we can build a good GUI and a software using this just like windows.Could you tell me how we can build a software for linux using this.I mean What tecnical knowledge is required?

**Comment by sdht0** [comment]
Hi Akash, thanks for using this code. 

You'll need to choose a programming language and a GUI Toolkit to build such programs. For example, I have used the Python programming language and the GUI is done using PyQt.

And this will work cross platform (Linux, WIndows, OS X) as long as Python and PyQt is installed
